function InternalSurfaces_NoTopologyPreserving(subjDir, noOfClasses, appDir, lsParams)

outputFilename = [lsParams.prefix  '_levelset_Result_' num2str(noOfClasses) 'classes.nii.gz'];
outputFilename = fullfile(lsParams.resultDir, outputFilename);

if exist(outputFilename, 'file')
  disp('InternalSurfaces_NoTopologyPreserving : ');
  disp(['File : ' outputFilename ' exists, returning']);
  return
end

postDir = ['post' num2str(noOfClasses)];

% ====================================================================== %
% signed pressure force is generated by blurring approximating the 0.5
% isosurface

wmRoiFile = 'wm_membership_roi.nii.gz';
wmRoiFile = fullfile(subjDir, postDir, wmRoiFile);
[wm_membership, header] = loadAnalyze(wmRoiFile, 'Real');

signedPressureForce_internalsurf = 2 * wm_membership - 1;

filename = ['SPF_internalSurfaceMap_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(signedPressureForce_internalsurf, header, filename, 'Real');

% ====================================================================== %
% signed pressure force is generated by blurring approximating the 0.5
% isosurface of gray matter surfaces

gmRoiFile = 'gm_membership_roi.nii.gz';
gmRoiFile = fullfile(subjDir, postDir, gmRoiFile);
[gm_membership, header] = loadAnalyze(gmRoiFile, 'Real');

signedPressureForce_externalsurf = 2 * (wm_membership + gm_membership) - 1;

filename = ['SPF_externalSurfaceMap_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(signedPressureForce_externalsurf, header, filename, 'Real');


% ====================================================================== %
% initialze the signed distance function (SDF) from the isosurface of binary
% segmentation volume
wmNoHolesFile = ['wm_seg_' num2str(noOfClasses) 'classes_roi_noholes.nii.gz'];
wmNoHolesFile = fullfile(subjDir, 'result', wmNoHolesFile);
[wmSegRoiNoHoles, header] = loadAnalyze(wmNoHolesFile, 'Grey');

SDF = createApproximated_SDF(wmSegRoiNoHoles, header, appDir);

filename = ['signedDistanceFunction_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(SDF, header, filename, 'Real');

% ====================================================================== %
% perform the internal surface propagation using levelset

% filename = 'wm_seg_roi_noholes.hdr';
% [imagedata, header] = loadAnalyze(filename, 'Grey');
% 

% filename = 'SignedDistanceFunction.hdr';
% [SDF, header] = loadAnalyze(filename, 'Real');

% filename = 'SPF_internalSurfaceMap.hdr';
% [signedPressureForce_internalsurf, header] = loadAnalyze(filename, 'Real');

% perform the level set propagation
%---------------------------------------------------------------------------

data0 = SDF;
normalSpeed = signedPressureForce_internalsurf;

% bValue = -0.02;
%
% accuracy = 'medium';
% tMax_ReIntialize = 2.5;
% errorMax = 0.05;
%
% resultDir = 'levelset_medium_ReInitialization_FullHead_Internal';
%
% tMax = 25;                   % End time.
% plotSteps = 100;              % How many intermediate plots to produce?
%
% prefix = 'Internal';
% flag_outside = 0; % target surface must be outside the data0 surface
% flag_inside = 0; % target surface must be inside the data0 surface
%--------------------------------------------------------------------------

levelSet_External_InternalSurface(wmSegRoiNoHoles, header, normalSpeed, data0, lsParams, noOfClasses);

    % ====================================================================== %
