function InternalSurfaces_NoTopologyPreserving(subjDir, noOfClasses, appDir)

prefix = 'prefix';

postDir = ['post' num2str(noOfClasses)];

filename = [prefix  '_levelset_Result.nii.gz'];
filename = fullfile(subjDir, 'cortexRecon', filename);

if exist(filename, 'file')
  disp('InternalSurfaces_NoTopologyPreserving : ');
  disp(['File : ' filename ' exists, returning']);
  return
end

% ====================================================================== %
% signed pressure force is generated by blurring approximating the 0.5
% isosurface

wmRoiFile = 'wm_membership_roi.nii.gz';
wmRoiFile = fullfile(subjDir, postDir, wmRoiFile);
[wm_membership, header] = loadAnalyze(wmRoiFile, 'Real');

signedPressureForce_internalsurf = 2 * wm_membership - 1;

filename = 'SPF_internalsurfaces_membership.nii.gz';
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(signedPressureForce_internalsurf, header, filename, 'Real');
% saveAnalyze(2048*signedPressureForce_internalsurf, header, 'SPF_internalsurfaces_membership_rview.hdr', 'Real');

% ====================================================================== %
% signed pressure force is generated by blurring approximating the 0.5
% isosurface of gray matter surfaces

gmRoiFile = 'gm_membership_roi.nii.gz';
gmRoiFile = fullfile(subjDir, postDir, gmRoiFile);
[gm_membership, header] = loadAnalyze(gmRoiFile, 'Real');

signedPressureForce_externalsurf = 2 * (wm_membership + gm_membership) - 1;

filename = 'SPF_externalsurfaces_membership.nii.gz';
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(signedPressureForce_externalsurf, header, filename, 'Real');
% saveAnalyze(2048*signedPressureForce_externalsurf, header, 'SPF_externalsurfaces_membership_rview.hdr', 'Real');


% ====================================================================== %
% initialze the signed distance function (SDF) from the isosurface of binary
% segmentation volume
wmNoHolesFile = ['wm_seg_' num2str(noOfClasses) 'classes_roi_noholes.nii.gz'];
wmNoHolesFile = fullfile(subjDir, 'result', wmNoHolesFile);
[data, header] = loadAnalyze(wmNoHolesFile, 'Grey');

SDF = CreateApproximated_SDF(data, header, appDir);

filename = 'signedDistanceFunction.nii.gz';
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(SDF, header, filename, 'Real');

% ====================================================================== %
% perform the internal surface propagation using levelset

 filename = 'wm_seg_roi_noholes.hdr';
[imagedata, header] = loadAnalyze(filename, 'Grey');

filename = 'SignedDistanceFunction.hdr';
[SDF, header] = loadAnalyze(filename, 'Real');

filename = 'SPF_internalsurfaces_membership.hdr';
[signedPressureForce_internalsurf, header] = loadAnalyze(filename, 'Real');

xsize = header.xsize;
ysize = header.ysize;
zsize = header.zsize;

xvoxelsize = header.xvoxelsize;
yvoxelsize = header.yvoxelsize;
zvoxelsize = header.zvoxelsize;

% perform the level set propagation
%---------------------------------------------------------------------------
data0 = SDF;
normalSpeed = signedPressureForce_internalsurf;
% bValue = -0.02;
%
% accuracy = 'medium';
% tMax_ReIntialize = 2.5;
% errorMax = 0.05;
%
% resultDir = 'levelset_medium_ReInitialization_FullHead_Internal';
%
% tMax = 25;                   % End time.
% plotSteps = 100;              % How many intermediate plots to produce?
%
% prefix = 'Internal';
% flag_outside = 0; % target surface must be outside the data0 surface
% flag_inside = 0; % target surface must be inside the data0 surface
%--------------------------------------------------------------------------

LevelSet_External_InternalSurface_Script

    % ====================================================================== %
