function Reconstruction_External_GM_Enhanced_TH(subjDir, noOfClasses, appDir, lsParams)


outputFilename = [lsParams.prefix  '_levelset_Result_TH_' num2str(noOfClasses) 'classes.nii.gz'];
outputFilename = fullfile(lsParams.resultDir, outputFilename);

if exist(outputFilename, 'file')
  disp('Reconstruction_External_GM_Enhanced_TH : ');
  disp(['File : ' outputFilename ' exists, returning']);
  return
end

postDir = ['post' num2str(noOfClasses)];

% ====================================================================== %
% signed pressure force is generated by blurring approximating the 0.5
% isosurface of gray matter surfaces

wmRoiFile = 'wm_membership_roi.nii.gz';
wmRoiFile = fullfile(subjDir, postDir, wmRoiFile);
[wm_membership, header] = loadAnalyze(wmRoiFile, 'Real');

filename = 'enhanced_gm_membership.hdr';
filename = ['enhanced_gm_membership_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(lsParams.resultDir, filename);

if ~exist(filename, 'file')
  disp('Reconstruction_External_GM_Enhanced_TH :');
  disp('Cannot find enhanced GM file');
  disp(filename);
  disp('Reverting to ordinary GM file');

  filename = 'gm_membership_roi.nii.gz';
  filename = fullfile(subjDir, postDir, filename);
end

[gm_membership, header] = loadAnalyze(filename, 'Real');

SignedPressureForce_externalsurfaces = ...
  2 * (wm_membership + gm_membership) - 1;

% Following step over-writes a previously written file with the same name that
% was previously calculated using the ordinary GM membership file (i.e. not
% 'enhanced'.

filename = ['SPF_externalSurfaceMap_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(subjDir, 'cortexRecon', filename);
saveAnalyze(SignedPressureForce_externalsurfaces, header, filename, 'Real');
% saveAnalyze(2048*SignedPressureForce_externalsurfaces, header, 'SPF_externalSurfaceMap_rview.hdr', 'Real');

% ====================================================================== %
% perform the external surface propagation using levelset

filename = ['wm_seg_' num2str(noOfClasses) 'classes_roi_noholes.nii.gz'];
filename = fullfile(subjDir, 'result', filename);
[wmData, header] = loadAnalyze(filename, 'Grey');

filename = ['Internal_levelset_Result_' num2str(noOfClasses) 'classes.nii.gz'];
filename = fullfile(lsParams.resultDir, filename);
[SDF, header] = loadAnalyze(filename, 'Real');

%%% THE FOLLOWING LINES OPEN WHAT LOOKS LIKE AN EXTERNAL SURFACE MAP AND
%%% ASSIGNS IT TO A VARIABLE CALLED SPF INTERNAL SURFACES ... SEEMS
%%% INCORRECT.
%  filename = 'SPF_externalSurfaceMap.hdr';
%  [SignedPressureForce_internalsurfaces, header] = loadAnalyze(filename, 'Real');
% This file was written a few lines earlier, so just assign the data
% without doing a file read.
% This gives the following bizarre looking assignment.
SignedPressureForce_internalsurfaces = SignedPressureForce_externalsurfaces;

% perform the level set propagation
%---------------------------------------------------------------------------
data0 = SDF;

% See comments above, perhaps we should have read in SPF_internalSurfaceMap
% instead?
normalSpeed = SignedPressureForce_internalsurfaces;


% bValue = 0.02;
%
% accuracy = 'medium';
% tMax_ReIntialize = 2.5;
% errorMax = 0.05;
%
% resultDir = 'levelset_medium_External_GMEnhanced_topologyCorrection_26_6';
%
% tMax = 6;                   % End time.
% tPlot = 0.1;
% factorCFL = 0.2;
% reInitialStep = 0.25;
%
% prefix = 'External';
% flag_outside = 1; % target surface must be outside the data0 surface
% flag_inside = 0; % target surface must be inside the data0 surface
%
% saveFlag = 1;
thicknessSpeed = zeros(size(normalSpeed)) + eps;
%--------------------------------------------------------------------------
levelSet_External_InternalSurface_TP_MinTH(wmData, data0, normalSpeed, thicknessSpeed, header, lsParams, outputFilename);


